import { auth, db, storage } from './firebase.js';
import { prepareListingPhotos } from './image-utils.js';
import { createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js';
import { collection, query, where, getDocs, getDoc, addDoc, doc, updateDoc, deleteDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
import { ref, uploadBytes, getDownloadURL, deleteObject } from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-storage.js';
const MAX_PHOTOS=8;
const email=document.getElementById('email'),password=document.getElementById('password'),status=document.getElementById('auth-status'),form=document.getElementById('auth-form'),signedInBox=document.getElementById('signed-in-box'),signedInTools=document.getElementById('signed-in-tools'),signOutBtn=document.getElementById('sign-out'),intro=document.getElementById('account-intro'),myListings=document.getElementById('my-listings'),results=document.getElementById('my-listings-results'),savedItems=document.getElementById('saved-items'),savedResults=document.getElementById('saved-items-results'),incomingOffers=document.getElementById('incoming-offers'),incomingResults=document.getElementById('incoming-offers-results'),myOffers=document.getElementById('my-offers'),myOffersResults=document.getElementById('my-offers-results'),messages=document.getElementById('messages'),messagesResults=document.getElementById('messages-results');let listingCache=new Map();
function showSignedIn(u){form.hidden=true;form.style.setProperty('display','none','important');signedInBox.hidden=false;signedInTools.hidden=false;[myListings,savedItems,incomingOffers,myOffers,messages].forEach(x=>x.hidden=false);signedInBox.style.display='block';signedInTools.style.display='flex';intro.textContent='Welcome back. Manage your messages, offers, saved items, and listings here.';signedInBox.innerHTML=`<strong>Signed in as ${escapeHtml(u.email||'Paws It On member')}</strong>`;}
function showSignedOut(){[signedInBox,signedInTools,myListings,savedItems,incomingOffers,myOffers,messages].forEach(x=>{x.hidden=true;x.style.display='none'});form.hidden=false;form.style.setProperty('display','grid','important');intro.textContent='Sign in or create an account to buy and sell on Paws It On.';}
document.getElementById('create-account').onclick=async()=>{try{await createUserWithEmailAndPassword(auth,email.value.trim(),password.value);status.textContent='Account created. You are signed in.';}catch(e){status.textContent=friendly(e);}};document.getElementById('sign-in').onclick=async()=>{try{await signInWithEmailAndPassword(auth,email.value.trim(),password.value);status.textContent='Signed in.';}catch(e){status.textContent=friendly(e);}};signOutBtn.onclick=async()=>{await signOut(auth);status.textContent='Signed out.';};
onAuthStateChanged(auth,async u=>{if(!u){showSignedOut();return;}showSignedIn(u);await Promise.all([loadMessages(u.uid),loadIncomingOffers(u.uid),loadMyOffers(u.uid),loadSavedItems(u.uid),loadMyListings(u.uid)]);});
async function loadMessages(uid){messagesResults.innerHTML='<p>Loading messages…</p>';try{const snap=await getDocs(query(collection(db,'conversations'),where('participants','array-contains',uid))),convs=[];snap.forEach(d=>convs.push({id:d.id,...d.data()}));convs.sort((a,b)=>(b.updatedAt?.seconds||0)-(a.updatedAt?.seconds||0));if(!convs.length){messagesResults.innerHTML='<div class="empty-listings"><strong>No messages yet.</strong><p>Start a private conversation from any marketplace listing.</p></div>';updateUnreadBadge(0);return;}let unreadTotal=0;const rendered=[];for(const c of convs){const ms=await getDocs(collection(db,'conversations',c.id,'messages')),items=[];ms.forEach(d=>items.push({id:d.id,...d.data()}));items.sort((a,b)=>(a.createdAt?.seconds||0)-(b.createdAt?.seconds||0));const lastSeen=Number(localStorage.getItem(`pawsSeen_${uid}_${c.id}`)||0),unread=items.filter(m=>m.senderId!==uid&&(m.createdAt?.seconds||0)>lastSeen).length;unreadTotal+=unread;rendered.push(renderConversation(c,items,uid,unread);}messagesResults.innerHTML=rendered.join('');updateUnreadBadge(unreadTotal);messagesResults.querySelectorAll('[data-send-reply]').forEach(b=>b.onclick=sendReply);messagesResults.querySelectorAll('[data-open-conversation]').forEach(b=>b.onclick=()=>markConversationRead(uid,b.dataset.openConversation));}catch(e){console.error(e);messagesResults.innerHTML='<div class="empty-listings">Messages could not load.</div>';}}
function updateUnreadBadge(n){const badge=document.getElementById('message-unread-badge'),summary=document.getElementById('message-summary');if(badge){badge.textContent=n;badge.hidden=!n;}if(summary)summary.textContent=n?`You have ${n} unread message${n===1?'':'s'}.`:'You’re all caught up.';}
function renderConversation(c,items,uid,unread){const image=c.listingImage?`<img src="${escapeAttr(c.listingImage)}" alt="${escapeAttr(c.listingTitle||'Listing')}">`:'<div class="conversation-fallback">🐾</div>',role=c.sellerId===uid?'You are the seller':'You are the buyer',last=items.at(-1),preview=last?.text?escapeHtml(last.text.slice(0,90)):'No messages yet.',thread=items.length?items.map(m=>`<div class="message-bubble ${m.senderId===uid?'mine':''}"><p>${escapeHtml(m.text||'')}</p></div>`).join(''):'<p>No messages yet.</p>';return `<article class="conversation-card ${unread?'conversation-unread':''}" data-open-conversation="${escapeAttr(c.id)}">${image}<div><div class="inbox-heading"><span class="listing-state">${role}</span>${unread?`<span class="unread-pill">${unread} NEW</span>`:''}</div><h3>${escapeHtml(c.listingTitle||'Listing conversation')}</h3><p class="message-preview">${preview}</p><a class="mini-btn edit" href="listing.html?id=${encodeURIComponent(c.listingId||'')}">View Listing</a></div><div class="message-thread">${thread}</div><div class="reply-row"><textarea data-reply-text="${escapeAttr(c.id)}" maxlength="1000" placeholder="Write a reply…"></textarea><button class="mini-btn edit" data-send-reply="${escapeAttr(c.id)}">Send Reply</button><p class="listing-meta" data-reply-status="${escapeAttr(c.id)}"></p></div></article>`;}
function markConversationRead(uid,id){const card=messagesResults.querySelector(`[data-open-conversation="${CSS.escape(id)}"]`),times=[...card.querySelectorAll('.message-bubble')];localStorage.setItem(`pawsSeen_${uid}_${id}`,String(Math.floor(Date.now()/1000)));card.classList.remove('conversation-unread');card.querySelector('.unread-pill')?.remove();loadMessages(uid);}
async function sendReply(e){e.stopPropagation();const id=e.currentTarget.dataset.sendReply,textBox=messagesResults.querySelector(`[data-reply-text="${CSS.escape(id)}"]`),out=messagesResults.querySelector(`[data-reply-status="${CSS.escape(id)}"]`),text=textBox?.value.trim(),u=auth.currentUser;if(!text||!u)return;try{e.currentTarget.disabled=true;if(out)out.textContent='Sending…';await addDoc(collection(db,'conversations',id,'messages'),{senderId:u.uid,text,createdAt:serverTimestamp()});await updateDoc(doc(db,'conversations',id),{updatedAt:serverTimestamp()});localStorage.setItem(`pawsSeen_${u.uid}_${id}`,String(Math.floor(Date.now()/1000)));if(out)out.textContent='Reply sent.';if(textBox)textBox.value='';await loadMessages(u.uid);}catch(err){console.error(err);if(out)out.textContent='Message not sent. Messaging is unavailable for this conversation.';e.currentTarget.disabled=false;}}
async function loadIncomingOffers(uid){try{const s=await getDocs(query(collection(db,'offers'),where('sellerId','==',uid))),a=[];s.forEach(d=>a.push({id:d.id,...d.data()}));incomingResults.innerHTML=a.length?a.map(o=>`<article class="offer-card"><h3>${escapeHtml(o.listingTitle||'Listing')}</h3><p>Offer: <strong>$${Number(o.amount||0).toFixed(2)}</strong></p><span class="offer-state">${escapeHtml(o.status||'pending')}</span></article>`).join(''):'<div class="empty-listings">No offers yet.</div>';}catch(e){console.error(e);}}
async function loadMyOffers(uid){try{const s=await getDocs(query(collection(db,'offers'),where('buyerId','==',uid))),a=[];s.forEach(d=>a.push({id:d.id,...d.data()}));myOffersResults.innerHTML=a.length?a.map(o=>`<article class="offer-card"><h3>${escapeHtml(o.listingTitle||'Listing')}</h3><p>Your offer: <strong>$${Number(o.amount||0).toFixed(2)}</strong></p><span class="offer-state">${escapeHtml(o.status||'pending')}</span></article>`).join(''):'<div class="empty-listings">No offers sent yet.</div>';}catch(e){console.error(e);}}
async function loadSavedItems(uid){try{const s=await getDocs(query(collection(db,'favorites'),where('userId','==',uid))),f=[];s.forEach(d=>f.push({id:d.id,...d.data()}));const a=[];for(const v of f){const x=await getDoc(doc(db,'listings',v.listingId));if(x.exists())a.push({favoriteId:v.id,id:x.id,...x.data()});}savedResults.innerHTML=a.length?a.map(i=>`<article class="saved-card"><div><h3>${escapeHtml(i.title||'Listing')}</h3><p><strong>$${Number(i.price||0).toFixed(2)}</strong></p><a class="mini-btn edit" href="listing.html?id=${encodeURIComponent(i.id)}">View Item</a></div></article>`).join(''):'<div class="empty-listings">No saved items yet.</div>';}catch(e){console.error(e);}}
async function loadMyListings(uid){try{const s=await getDocs(query(collection(db,'listings'),where('sellerId','==',uid))),a=[];s.forEach(d=>a.push({id:d.id,...d.data()}));listingCache=new Map(a.map(i=>[i.id,i]));results.innerHTML=a.length?a.map(i=>`<article class="seller-listing"><span class="listing-state">${escapeHtml(i.status||'active')}</span><h3>${escapeHtml(i.title||'Listing')}</h3><p><strong>$${Number(i.price||0).toFixed(2)}</strong></p><a class="mini-btn edit" href="listing.html?id=${encodeURIComponent(i.id)}">View Listing</a></article>`).join(''):'<div class="empty-listings">No listings yet.</div>';}catch(e){console.error(e);}}
function friendly(e){const c=e?.code||'';if(c.includes('email-already-in-use'))return'That email already has an account. Try Sign In.';if(c.includes('invalid-credential'))return'Email or password did not match.';if(c.includes('weak-password'))return'Use a password with at least 6 characters.';return'Could not complete that request.';}function escapeHtml(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}function escapeAttr(s){return escapeHtml(s).replace(/`/g,'&#96;');}
