import {auth,db} from './firebase.js';
import {onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js';
import {doc,getDoc,updateDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
const params=new URLSearchParams(location.search),offerId=params.get('offer');
const form=document.getElementById('shipping-form'),status=document.getElementById('checkout-status'),button=document.getElementById('continue-btn'),paymentBox=document.getElementById('payment-test'),paymentBtn=document.getElementById('test-payment-btn'),paymentStatus=document.getElementById('payment-status');
let currentOffer=null;
const money=n=>`$${Number(n||0).toFixed(2)}`;
function showPaymentState(o){if(!o)return;if(o.checkoutStage==='paid_test'||o.paymentStatus==='paid_test'){paymentBox.hidden=false;paymentBtn.disabled=true;paymentBtn.textContent='Test Payment Complete';paymentStatus.textContent='📣 Test payment successful. The seller can now prepare this order for shipping.';return;}if(o.shippingAddress||o.checkoutStage==='awaiting_payment'){paymentBox.hidden=false;paymentBtn.disabled=false;paymentBtn.textContent='Run Test Payment';paymentStatus.textContent='';}}
onAuthStateChanged(auth,async user=>{if(!user){status.textContent='Please sign in to continue checkout.';button.disabled=true;return;}if(!offerId){status.textContent='This checkout link is missing its offer number.';button.disabled=true;return;}try{const snap=await getDoc(doc(db,'offers',offerId));if(!snap.exists())throw new Error('Offer not found');const o={id:snap.id,...snap.data()};if(o.buyerId!==user.uid||o.status!=='accepted'||o.fulfillmentMethod!=='shipping')throw new Error('Checkout is not available for this offer');currentOffer=o;const price=Number(o.counterAmount||o.amount||0);document.getElementById('item-title').textContent=o.listingTitle||'Your purchase';document.getElementById('item-price').textContent=money(price);document.getElementById('subtotal').textContent=money(price);if(o.shippingAddress){document.getElementById('ship-name').value=o.shippingAddress.fullName||'';document.getElementById('ship-street').value=o.shippingAddress.street||'';document.getElementById('ship-unit').value=o.shippingAddress.unit||'';document.getElementById('ship-city').value=o.shippingAddress.city||'';document.getElementById('ship-state').value=o.shippingAddress.state||'';document.getElementById('ship-zip').value=o.shippingAddress.zip||'';}showPaymentState(o);}catch(e){console.error(e);status.textContent='This shipping checkout is not available.';button.disabled=true;}});
form.addEventListener('submit',async e=>{e.preventDefault();const user=auth.currentUser;if(!user||!currentOffer)return;button.disabled=true;button.textContent='Saving…';status.textContent='';const address={fullName:document.getElementById('ship-name').value.trim(),street:document.getElementById('ship-street').value.trim(),unit:document.getElementById('ship-unit').value.trim(),city:document.getElementById('ship-city').value.trim(),state:document.getElementById('ship-state').value.trim().toUpperCase(),zip:document.getElementById('ship-zip').value.trim()};try{await updateDoc(doc(db,'offers',offerId),{shippingAddress:address,checkoutStage:'awaiting_payment',shippingAddressSavedAt:serverTimestamp(),updatedAt:serverTimestamp()});currentOffer={...currentOffer,shippingAddress:address,checkoutStage:'awaiting_payment'};status.textContent='🐾 Shipping address saved! Run the test payment below.';button.textContent='Shipping Saved';showPaymentState(currentOffer);}catch(err){console.error(err);status.textContent='Shipping could not be saved yet.';button.disabled=false;button.textContent='Save Shipping & Continue';}});
paymentBtn.addEventListener('click',async()=>{const user=auth.currentUser;if(!user||!currentOffer||!currentOffer.shippingAddress)return;paymentBtn.disabled=true;paymentBtn.textContent='Processing Test Payment…';paymentStatus.textContent='';try{await updateDoc(doc(db,'offers',offerId),{paymentStatus:'paid_test',checkoutStage:'paid_test',testPaidAt:serverTimestamp(),updatedAt:serverTimestamp()});currentOffer={...currentOffer,paymentStatus:'paid_test',checkoutStage:'paid_test'};showPaymentState(currentOffer);}catch(err){console.error(err);paymentStatus.textContent='Test payment could not be recorded yet.';paymentBtn.disabled=false;paymentBtn.textContent='Run Test Payment';}});