import {auth,db} from './firebase.js';
import {onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js';
import {collection,query,where,getDocs,doc,getDoc,setDoc,addDoc,updateDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
const list=document.getElementById('inbox-list'),panel=document.getElementById('thread-panel'),content=document.getElementById('thread-content'),summary=document.getElementById('messages-summary');let user=null,conversations=[];
onAuthStateChanged(auth,async u=>{user=u;if(!u){list.innerHTML='<div class="empty"><strong>Sign in to see your messages.</strong><p><a class="btn btn-teal" href="account.html">Go to My Paws It On</a></p></div>';summary.textContent='';return;}await loadInbox();});
async function loadInbox(){list.innerHTML='<p>Loading messages…</p>';try{const s=await getDocs(query(collection(db,'conversations'),where('participants','array-contains',user.uid)));conversations=[];for(const d of s.docs){const c={id:d.id,...d.data()};const ms=await getDocs(collection(db,'conversations',d.id,'messages'));c.messages=ms.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(a.createdAt?.seconds||0)-(b.createdAt?.seconds||0));c.last=c.messages.at(-1)||null;c.unread=await unreadCount(c);conversations.push(c);}conversations.sort((a,b)=>(b.last?.createdAt?.seconds||b.updatedAt?.seconds||0)-(a.last?.createdAt?.seconds||a.updatedAt?.seconds||0));const total=conversations.reduce((n,c)=>n+c.unread,0);summary.textContent=total?`You have ${total} unread message${total===1?'':'s'}.`:'You’re all caught up.';list.innerHTML=conversations.length?conversations.map(renderCard).join(''):'<div class="empty"><strong>No conversations yet.</strong><p>When you message a seller or receive a buyer message, it will appear here.</p></div>';list.querySelectorAll('[data-conversation]').forEach(x=>x.onclick=()=>openConversation(x.dataset.conversation));}catch(e){console.error(e);list.innerHTML='<div class="empty">Messages could not load right now.</div>';}}
async function unreadCount(c){let seen=0;try{const r=await getDoc(doc(db,'messageReads',`${user.uid}_${c.id}`));seen=r.exists()?(r.data().lastReadSeconds||0):0;}catch(e){seen=Number(localStorage.getItem(`pawsSeen_${user.uid}_${c.id}`)||0);}return c.messages.filter(m=>m.senderId!==user.uid&&(m.createdAt?.seconds||0)>seen).length;}
function renderCard(c){const img=c.listingImage?`<img src="${attr(c.listingImage)}" alt="${attr(c.listingTitle||'Listing')}">`:'<div class="inbox-fallback">🐾</div>',preview=esc(c.last?.text||'No messages yet.'),time=formatTime(c.last?.createdAt?.seconds||c.updatedAt?.seconds||0),role=c.sellerId===user.uid?'Seller':'Buyer';return `<article class="inbox-card ${c.unread?'unread':''}" data-conversation="${attr(c.id)}">${img}<div><div class="meta-row"><span class="role">You’re the ${role}</span>${c.unread?`<span class="unread-pill">${c.unread} NEW</span>`:''}</div><h3>${esc(c.listingTitle||'Listing conversation')}</h3><p class="preview">${preview}</p></div><div class="time">${time}</div></article>`;}
async function openConversation(id){const c=conversations.find(x=>x.id===id);if(!c)return;panel.classList.add('open');const thread=c.messages.map(m=>`<div class="bubble ${m.senderId===user.uid?'mine':''}"><p>${esc(m.text||'')}</p></div>`).join('');content.innerHTML=`<div class="thread-top"><div><span class="role">${c.sellerId===user.uid?'You’re the seller':'You’re the buyer'}</span><h2>${esc(c.listingTitle||'Conversation')}</h2></div><a class="mini-btn edit" href="listing.html?id=${encodeURIComponent(c.listingId||'')}">View Listing</a></div><div class="thread-messages">${thread}</div><div class="reply-box"><textarea id="thread-reply" maxlength="1000" placeholder="Write a reply…"></textarea><button id="send-thread-reply" class="btn btn-teal">Send Reply</button><p id="thread-status" class="thread-status"></p></div>`;await markRead(c);document.getElementById('send-thread-reply').onclick=()=>sendReply(c);panel.scrollIntoView({behavior:'smooth',block:'start'});}
async function markRead(c){const seconds=Math.floor(Date.now()/1000);localStorage.setItem(`pawsSeen_${user.uid}_${c.id}`,String(seconds));try{await setDoc(doc(db,'messageReads',`${user.uid}_${c.id}`),{userId:user.uid,conversationId:c.id,lastReadSeconds:seconds,updatedAt:serverTimestamp()},{merge:true});}catch(e){console.warn('Read receipt stored locally only',e);}c.unread=0;const total=conversations.reduce((n,x)=>n+x.unread,0);summary.textContent=total?`You have ${total} unread message${total===1?'':'s'}.`:'You’re all caught up.';const card=list.querySelector(`[data-conversation="${CSS.escape(c.id)}"]`);card?.classList.remove('unread');card?.querySelector('.unread-pill')?.remove();}
async function sendReply(c){const box=document.getElementById('thread-reply'),out=document.getElementById('thread-status'),text=box.value.trim();if(!text)return;try{out.textContent='Sending…';await addDoc(collection(db,'conversations',c.id,'messages'),{senderId:user.uid,text,createdAt:serverTimestamp()});await updateDoc(doc(db,'conversations',c.id),{updatedAt:serverTimestamp()});box.value='';out.textContent='Reply sent.';await loadInbox();await openConversation(c.id);}catch(e){console.error(e);out.textContent='Message not sent. Messaging is unavailable for this conversation.';}}
function formatTime(s){if(!s)return'';const d=new Date(s*1000),now=new Date();return d.toDateString()===now.toDateString()?d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):d.toLocaleDateString([],{month:'short',day:'numeric'});}function esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}function attr(s){return esc(s).replace(/`/g,'&#96;');}
