import {auth,db} from './firebase.js';
import {createUserWithEmailAndPassword,signInWithEmailAndPassword,signOut,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js';
import {collection,query,where,getDocs,getDoc,doc,setDoc,deleteDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
const $=id=>document.getElementById(id),login=$('login-card'),profile=$('profile-card'),form=$('auth-form'),intro=$('account-intro'),status=$('auth-status'),pstatus=$('profile-status'),view=$('profile-view'),editor=$('profile-editor');
let currentProfile={displayName:'',bio:'',pets:{}};
$('create-account').onclick=async()=>{try{await createUserWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);status.textContent='Account created.';}catch(e){status.textContent=friendly(e)}};
$('sign-in').onclick=async()=>{try{await signInWithEmailAndPassword(auth,$('email').value.trim(),$('password').value);status.textContent='Signed in.';}catch(e){status.textContent=friendly(e)}};
$('sign-out').onclick=()=>signOut(auth);$('save-profile').onclick=saveProfile;$('edit-profile').onclick=()=>setEditing(true);$('cancel-edit').onclick=()=>{fillEditor(currentProfile);setEditing(false)};
onAuthStateChanged(auth,async u=>{if(!u){profile.hidden=true;login.hidden=false;form.hidden=false;intro.textContent='Sign in or create an account to manage your Paws It On profile.';return;}login.hidden=true;profile.hidden=false;$('profile-email').textContent=u.email||'';const created=u.metadata?.creationTime?new Date(u.metadata.creationTime):null;$('member-since').textContent=created?`Member since ${created.toLocaleDateString(undefined,{month:'long',year:'numeric'})}`:'Paws It On member';await Promise.all([loadProfile(u),loadStats(u.uid),loadBlocks(u.uid)]);});
function setEditing(on){view.hidden=on;editor.hidden=!on;if(on)pstatus.textContent='';}
function fillEditor(d){const pets=d.pets||{};$('display-name').value=d.displayName||'';$('bio').value=d.bio||'';for(const k of ['dogs','cats','rabbits','horses','birds','reptiles','farm','other'])$(`pet-${k}`).value=Number(pets[k]||0);}
function renderProfile(d){currentProfile=d||{displayName:'',bio:'',pets:{}};$('profile-heading').textContent=d.displayName||'Paws It On Member';$('bio-view').textContent=d.bio||'No bio added yet.';const labels={dogs:['🐶','Dog'],cats:['🐱','Cat'],rabbits:['🐰','Rabbit'],horses:['🐴','Horse'],birds:['🐦','Bird'],reptiles:['🐍','Reptile'],farm:['🐔','Farm animal'],other:['🐾','Other pet']},chips=[];for(const [k,[emoji,name]] of Object.entries(labels)){const n=Number(d.pets?.[k]||0);if(n>0)chips.push(`<span class="pet-chip">${emoji} ${n} ${esc(name)}${n===1?'':'s'}</span>`);}$('pets-view').innerHTML=chips.length?chips.join(''):'<span class="pet-chip">No pets added yet</span>';fillEditor(d);}
async function loadProfile(u){try{const s=await getDoc(doc(db,'profiles',u.uid));if(!s.exists()){renderProfile({displayName:'',bio:'',pets:{}});setEditing(true);return;}renderProfile(s.data());setEditing(false);}catch(e){console.error(e);pstatus.textContent='Profile details could not load.';}}
async function saveProfile(){const u=auth.currentUser;if(!u)return;const pets={};for(const k of ['dogs','cats','rabbits','horses','birds','reptiles','farm','other'])pets[k]=Math.max(0,Math.min(99,Number($(`pet-${k}`).value)||0));const data={displayName:$('display-name').value.trim().slice(0,60),bio:$('bio').value.trim().slice(0,500),pets,email:u.email||'',updatedAt:serverTimestamp(),createdAt:u.metadata?.creationTime||''};try{pstatus.textContent='Saving…';await setDoc(doc(db,'profiles',u.uid),data,{merge:true});renderProfile(data);setEditing(false);pstatus.textContent='';}catch(e){console.error(e);pstatus.textContent='Profile could not be saved.';}}
async function loadStats(uid){try{const[ls,fs]=await Promise.all([getDocs(query(collection(db,'listings'),where('sellerId','==',uid))),getDocs(query(collection(db,'favorites'),where('userId','==',uid)))]);let listings=0,sold=0;ls.forEach(x=>{if(x.data().status==='sold')sold++;else listings++;});$('stat-listings').textContent=listings;$('stat-sold').textContent=sold;$('stat-saved').textContent=fs.size;try{const os=await getDocs(query(collection(db,'offers'),where('buyerId','==',uid)));let purchases=0;os.forEach(x=>{if(x.data().status==='accepted')purchases++;});$('stat-purchases').textContent=purchases;}catch{}}catch(e){console.error(e)}}
async function loadBlocks(uid){try{const s=await getDocs(query(collection(db,'blocks'),where('blockerId','==',uid))),a=[];s.forEach(x=>a.push({id:x.id,...x.data()}));$('blocked-results').innerHTML=a.length?a.map(x=>`<div class="blocked-item"><strong>Blocked member</strong><br><small>Account ending …${esc((x.blockedUserId||'').slice(-6))}</small> <button class="mini-btn" data-unblock="${esc(x.id)}">Unblock</button></div>`).join(''):'<p>No blocked members.</p>';$('blocked-results').querySelectorAll('[data-unblock]').forEach(b=>b.onclick=async()=>{if(confirm('Unblock this member?')){await deleteDoc(doc(db,'blocks',b.dataset.unblock));loadBlocks(uid)}});}catch(e){$('blocked-results').innerHTML='<p>Blocked members unavailable.</p>';}}
function friendly(e){const c=e?.code||'';if(c.includes('email-already-in-use'))return'That email already has an account. Try Sign In.';if(c.includes('invalid-credential'))return'Email or password did not match.';if(c.includes('weak-password'))return'Use a password with at least 6 characters.';return'Could not complete that request.'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}