import {auth,db} from './firebase.js';
import {onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js';
import {collection,query,where,getDocs} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
const root=document.getElementById('purchase-results');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const orderNo=o=>`PIO-${String(o.id||'').slice(0,8).toUpperCase()}`;
const dateText=o=>{const d=(o.completedAt||o.testPaidAt||o.shippingAddressSavedAt||o.acceptedAt)?.toDate?.();return d?d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'In progress';};
function stateInfo(o){if(o.status==='completed')return {label:'COMPLETED',title:`📣 ${o.fulfillmentMethod==='pickup'?'Local Pickup':'Shipping'} complete`,note:'This transaction has been completed and is saved in your purchase history.'};if(o.fulfillmentMethod==='shipping'&&o.checkoutStage==='shipped')return {label:'SHIPPED',title:'📦 Your order has shipped',note:'The seller marked this order as shipped.'};if(o.fulfillmentMethod==='shipping'&&['paid','paid_test','ready_to_ship'].includes(o.checkoutStage))return {label:'PAID',title:'📣 Payment complete — preparing to ship',note:'Your payment is recorded and the seller can prepare the order for shipping.'};if(o.fulfillmentMethod==='shipping'&&o.checkoutStage==='awaiting_payment')return {label:'AWAITING PAYMENT',title:'📦 Shipping address saved',note:'Checkout is waiting for payment.'};return {label:'IN PROGRESS',title:'🐾 Purchase in progress',note:'This purchase is still being completed.'};}
onAuthStateChanged(auth,async u=>{if(!u){root.innerHTML='<div class="empty-listings"><strong>Sign in to see your purchases.</strong></div>';return;}try{const snap=await getDocs(query(collection(db,'offers'),where('buyerId','==',u.uid))),a=[];snap.forEach(d=>{const o={id:d.id,...d.data()};const activeShipping=o.status==='accepted'&&o.fulfillmentMethod==='shipping'&&['awaiting_payment','paid','paid_test','ready_to_ship','shipped'].includes(o.checkoutStage);if(o.status==='completed'||activeShipping)a.push(o);});a.sort((x,y)=>((y.completedAt||y.testPaidAt||y.shippingAddressSavedAt||y.acceptedAt)?.seconds||0)-((x.completedAt||x.testPaidAt||x.shippingAddressSavedAt||x.acceptedAt)?.seconds||0));root.innerHTML=a.length?`<div class="purchase-grid">${a.map(render).join('')}</div>`:'<div class="empty-listings"><strong>No purchases yet.</strong><p>Paid shipped orders and completed pickup orders will appear here.</p></div>';}catch(e){console.error(e);root.innerHTML='<div class="empty-listings">Purchases could not load.</div>';}});
function render(o){const method=o.fulfillmentMethod==='pickup'?'Local Pickup':o.fulfillmentMethod==='shipping'?'Shipping':'Purchase';const s=stateInfo(o);const checkout=o.status==='accepted'&&o.fulfillmentMethod==='shipping'&&o.checkoutStage==='awaiting_payment'?`<a class="mini-btn sold" href="checkout.html?offer=${encodeURIComponent(o.id)}">Continue Checkout</a>`:'';return `<article class="purchase-card"><span class="purchase-state">${esc(s.label)}</span><h3>${esc(o.listingTitle||'Purchase')}</h3><p class="purchase-price">$${Number(o.counterAmount||o.amount||0).toFixed(2)}</p><p><strong>Transaction:</strong> ${esc(orderNo(o))}<br><strong>Updated:</strong> ${esc(dateText(o))}<br><strong>Delivery:</strong> ${esc(method)}</p><div class="purchase-note"><strong>${s.title}</strong><p>${esc(s.note)}</p></div><div class="listing-actions"><a class="mini-btn edit" href="messages.html">Messages</a>${checkout}</div></article>`;}