import {auth,db} from './firebase.js';
import {onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js';
import {collection,query,where,getDocs,doc,getDoc,updateDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
const root=document.getElementById('purchase-results');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const orderNo=o=>`PIO-${String(o.id||'').slice(0,8).toUpperCase()}`;
const dateText=o=>{const d=(o.completedAt||o.shippedAt||o.testPaidAt||o.shippingAddressSavedAt||o.acceptedAt)?.toDate?.();return d?d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'In progress';};
function stateInfo(o){if(o.status==='completed')return {label:'COMPLETED',className:'completed',summary:o.fulfillmentMethod==='pickup'?'Local pickup complete':'Shipping complete'};if(o.fulfillmentMethod==='shipping'&&o.checkoutStage==='shipped')return {label:'SHIPPED',className:'shipped',summary:'Order shipped'};if(o.fulfillmentMethod==='shipping'&&['paid','paid_test','ready_to_ship'].includes(o.checkoutStage))return {label:'PAID',className:'paid',summary:'Preparing to ship'};if(o.fulfillmentMethod==='shipping'&&o.checkoutStage==='awaiting_payment')return {label:'AWAITING PAYMENT',className:'awaiting',summary:'Checkout waiting for payment'};return {label:'IN PROGRESS',className:'progress',summary:'Purchase in progress'};}
async function loadPurchases(u){try{const snap=await getDocs(query(collection(db,'offers'),where('buyerId','==',u.uid))),a=[];snap.forEach(d=>{const o={id:d.id,...d.data()};const activeShipping=o.status==='accepted'&&o.fulfillmentMethod==='shipping'&&['awaiting_payment','paid','paid_test','ready_to_ship','shipped'].includes(o.checkoutStage);if(o.status==='completed'||activeShipping)a.push(o);});a.sort((x,y)=>((y.completedAt||y.shippedAt||y.testPaidAt||y.shippingAddressSavedAt||y.acceptedAt)?.seconds||0)-((x.completedAt||x.shippedAt||x.testPaidAt||x.shippingAddressSavedAt||x.acceptedAt)?.seconds||0));root.innerHTML=a.length?`<div class="purchase-table"><div class="purchase-head"><span>Item</span><span>Status</span><span>Delivery</span><span>Price</span><span>Date</span><span>Actions</span></div>${a.map(render).join('')}</div>`:'<div class="empty-listings"><strong>No purchases yet.</strong><p>Paid shipped orders and completed pickup orders will appear here.</p></div>';}catch(e){console.error(e);root.innerHTML='<div class="empty-listings">Purchases could not load.</div>';}}
onAuthStateChanged(auth,u=>{if(!u){root.innerHTML='<div class="empty-listings"><strong>Sign in to see your purchases.</strong></div>';return;}loadPurchases(u);});
root.addEventListener('click',async e=>{const button=e.target.closest('[data-received]');if(!button)return;const u=auth.currentUser,id=button.dataset.received;if(!u||!id)return;if(!confirm('Confirm that you received this order? This will complete the transaction.'))return;const old=button.textContent;try{button.disabled=true;button.textContent='Completing…';const ref=doc(db,'offers',id),snap=await getDoc(ref);if(!snap.exists())throw new Error('Purchase not found');const o=snap.data();if(o.buyerId!==u.uid||o.status!=='accepted'||o.fulfillmentMethod!=='shipping'||o.checkoutStage!=='shipped')throw new Error('Purchase is not ready to complete');await updateDoc(ref,{status:'completed',checkoutStage:'completed',completedAt:serverTimestamp(),receivedAt:serverTimestamp(),updatedAt:serverTimestamp()});await loadPurchases(u);}catch(err){console.error(err);button.disabled=false;button.textContent=old;alert('This order could not be completed yet. If Firebase blocks it, we will update the rule.');}});
function render(o){const s=stateInfo(o),price=Number(o.counterAmount||o.amount||0).toFixed(2),image=o.listingImage||'',method=o.fulfillmentMethod==='pickup'?'📍 Local pickup':o.fulfillmentMethod==='shipping'?'📦 Shipping':'Purchase';const tracking=o.fulfillmentMethod==='shipping'&&o.trackingNumber?`<div class="delivery-sub">${esc(o.shippingCarrier||'Carrier')}: ${esc(o.trackingNumber)}</div>`:'';const checkout=o.status==='accepted'&&o.fulfillmentMethod==='shipping'&&o.checkoutStage==='awaiting_payment'?`<a class="mini-btn sold" href="checkout.html?offer=${encodeURIComponent(o.id)}">Continue Checkout</a>`:'';const received=o.status==='accepted'&&o.fulfillmentMethod==='shipping'&&o.checkoutStage==='shipped'?`<button class="mini-btn sold" data-received="${esc(o.id)}">I Received It</button>`:'';const primaryAction=checkout||received||'<a class="mini-btn edit" href="messages.html">Messages</a>';return `<article class="purchase-row"><div class="purchase-item">${image?`<img src="${esc(image)}" alt="${esc(o.listingTitle||'Purchase')}">`:'<div class="purchase-fallback">🐾</div>'}<div><h3>${esc(o.listingTitle||'Purchase')}</h3><div class="purchase-sub">Transaction ${esc(orderNo(o))}</div></div></div><div><span class="status-pill ${esc(s.className)}">${esc(s.label)}</span><div class="purchase-sub">${esc(s.summary)}</div></div><div><strong>${method}</strong>${tracking}</div><div class="purchase-money">$${price}</div><div class="purchase-date">${esc(dateText(o))}</div><div class="purchase-actions">${primaryAction}${primaryAction.includes('Messages')?'':`<a class="mini-btn edit" href="messages.html">Messages</a>`}</div></article>`;}