import {auth,db} from './firebase.js';
import {onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js';
import {collection,query,where,getDocs,doc,getDoc,updateDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
const root=document.getElementById('sales-results');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const orderNo=o=>`PIO-${String(o.id||'').slice(0,8).toUpperCase()}`;
const dateText=o=>{const d=(o.completedAt||o.shippedAt||o.testPaidAt||o.shippingAddressSavedAt||o.acceptedAt)?.toDate?.();return d?d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'In progress';};
function stateInfo(o){if(o.status==='completed')return {label:'SOLD',sub:o.fulfillmentMethod==='pickup'?'Local pickup complete':'Shipping complete'};if(o.fulfillmentMethod==='shipping'&&o.checkoutStage==='shipped')return {label:'SHIPPED',sub:'Order shipped'};if(o.fulfillmentMethod==='shipping'&&['paid','paid_test','ready_to_ship'].includes(o.checkoutStage))return {label:'PAID',sub:'Ready to ship'};return {label:'IN PROGRESS',sub:'Sale in progress'};}
async function loadSales(u){try{const snap=await getDocs(query(collection(db,'offers'),where('sellerId','==',u.uid))),a=[];snap.forEach(d=>{const o={id:d.id,...d.data()};const paidShipping=o.status==='accepted'&&o.fulfillmentMethod==='shipping'&&['paid','paid_test','ready_to_ship','shipped'].includes(o.checkoutStage);if(o.status==='completed'||paidShipping)a.push(o);});a.sort((x,y)=>((y.completedAt||y.shippedAt||y.testPaidAt||y.shippingAddressSavedAt||y.acceptedAt)?.seconds||0)-((x.completedAt||x.shippedAt||x.testPaidAt||x.shippingAddressSavedAt||x.acceptedAt)?.seconds||0));root.innerHTML=a.length?`<div class="sale-table"><div class="sale-head"><div>ITEM</div><div>STATUS</div><div>DELIVERY</div><div>PRICE</div><div>DATE</div><div>ACTIONS</div></div>${a.map(render).join('')}</div>`:'<div class="empty-listings"><strong>No sales yet.</strong><p>Paid shipped orders and completed pickup sales will appear here.</p></div>';}catch(e){console.error(e);root.innerHTML='<div class="empty-listings">Sales could not load.</div>';}}
onAuthStateChanged(auth,u=>{if(!u){root.innerHTML='<div class="empty-listings"><strong>Sign in to see your sales.</strong></div>';return;}loadSales(u);});
root.addEventListener('click',async e=>{const open=e.target.closest('[data-open-shipping]');if(open){const row=open.closest('.sale-row');row?.querySelector('.shipping-entry')?.removeAttribute('hidden');open.hidden=true;return;}const cancel=e.target.closest('[data-cancel-shipping]');if(cancel){const row=cancel.closest('.sale-row');row?.querySelector('.shipping-entry')?.setAttribute('hidden','');row?.querySelector('[data-open-shipping]')?.removeAttribute('hidden');return;}const button=e.target.closest('[data-save-shipping]');if(!button)return;const u=auth.currentUser,id=button.dataset.saveShipping,row=button.closest('.sale-row');if(!u||!id||!row)return;const carrier=row.querySelector('[data-carrier]')?.value.trim(),tracking=row.querySelector('[data-tracking]')?.value.trim();if(!carrier){alert('Choose a carrier first.');return;}if(!tracking){alert('Enter the tracking number first.');return;}if(!confirm(`Mark this order shipped with ${carrier} tracking ${tracking}?`))return;const old=button.textContent;try{button.disabled=true;button.textContent='Saving…';const ref=doc(db,'offers',id),snap=await getDoc(ref);if(!snap.exists())throw new Error('Sale not found');const o=snap.data();if(o.sellerId!==u.uid||o.status!=='accepted'||o.fulfillmentMethod!=='shipping'||!['paid','paid_test','ready_to_ship'].includes(o.checkoutStage))throw new Error('Sale is not ready to ship');await updateDoc(ref,{checkoutStage:'shipped',shippingCarrier:carrier,trackingNumber:tracking,shippedAt:serverTimestamp(),updatedAt:serverTimestamp()});await loadSales(u);}catch(err){console.error(err);button.disabled=false;button.textContent=old;alert('Shipping details could not be saved yet. If Firebase blocks it, we will update the rules.');}});
function render(o){const method=o.fulfillmentMethod==='pickup'?'📍 Local pickup':o.fulfillmentMethod==='shipping'?'📦 Shipping':'Sale',s=stateInfo(o),img=o.listingImage||'',tracking=o.fulfillmentMethod==='shipping'&&o.trackingNumber?`<div class="delivery-sub">${esc(o.shippingCarrier||'Carrier')}: ${esc(o.trackingNumber)}</div>`:'',shipButton=o.status==='accepted'&&o.fulfillmentMethod==='shipping'&&['paid','paid_test','ready_to_ship'].includes(o.checkoutStage)?`<button class="mini-btn sold" data-open-shipping>Mark Shipped</button><div class="shipping-entry" hidden><strong>📦 Shipping Details</strong><label>Carrier<select data-carrier><option value="">Choose carrier</option><option>USPS</option><option>UPS</option><option>FedEx</option><option>DHL</option><option>Other</option></select></label><label>Tracking number<input data-tracking autocomplete="off" placeholder="Enter tracking number"></label><div class="listing-actions"><button class="mini-btn sold" data-save-shipping="${esc(o.id)}">Save & Mark Shipped</button><button class="mini-btn edit" data-cancel-shipping>Cancel</button></div></div>`:'';return `<div class="sale-row"><div class="sale-item">${img?`<img src="${esc(img)}" alt="${esc(o.listingTitle||'Sale')}">`:'<div class="sale-fallback">🐾</div>'}<div><h3>${esc(o.listingTitle||'Sale')}</h3><div class="sale-sub">Transaction ${esc(orderNo(o))}</div></div></div><div><span class="status-pill ${esc(s.label.toLowerCase().replace(/\s+/g,'-'))}">${esc(s.label)}</span><div class="sale-sub">${esc(s.sub)}</div></div><div><strong>${esc(method)}</strong>${tracking}</div><div class="sale-money">$${Number(o.counterAmount||o.amount||0).toFixed(2)}</div><div class="sale-date">${esc(dateText(o))}</div><div class="sale-actions"><a class="mini-btn edit" href="messages.html">Messages</a>${shipButton}</div></div>`;}