import {auth,db} from './firebase.js';
import {onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js';
import {collection,query,where,getDocs,doc,getDoc,updateDoc,serverTimestamp} from 'https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js';
const root=document.getElementById('sales-results');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const orderNo=o=>`PIO-${String(o.id||'').slice(0,8).toUpperCase()}`;
const dateText=o=>{const d=(o.completedAt||o.shippedAt||o.testPaidAt||o.shippingAddressSavedAt||o.acceptedAt)?.toDate?.();return d?d.toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'}):'In progress';};
function stateInfo(o){if(o.status==='completed')return {label:'SOLD',title:`📣 ${o.fulfillmentMethod==='pickup'?'Local Pickup':'Shipping'} complete`,note:'This sale has been completed and is saved in your sales history.'};if(o.fulfillmentMethod==='shipping'&&o.checkoutStage==='shipped')return {label:'SHIPPED',title:'📦 Order shipped',note:'You marked this order as shipped. The buyer can now see the shipping status.'};if(o.fulfillmentMethod==='shipping'&&['paid','paid_test','ready_to_ship'].includes(o.checkoutStage))return {label:'PAID',title:'📣 PAID — Ready to Ship',note:'The buyer has paid. This order is ready for the shipping step.'};return {label:'IN PROGRESS',title:'🐾 Sale in progress',note:'This sale is still being completed.'};}
async function loadSales(u){try{const snap=await getDocs(query(collection(db,'offers'),where('sellerId','==',u.uid))),a=[];snap.forEach(d=>{const o={id:d.id,...d.data()};const paidShipping=o.status==='accepted'&&o.fulfillmentMethod==='shipping'&&['paid','paid_test','ready_to_ship','shipped'].includes(o.checkoutStage);if(o.status==='completed'||paidShipping)a.push(o);});a.sort((x,y)=>((y.completedAt||y.shippedAt||y.testPaidAt||y.shippingAddressSavedAt||y.acceptedAt)?.seconds||0)-((x.completedAt||x.shippedAt||x.testPaidAt||x.shippingAddressSavedAt||x.acceptedAt)?.seconds||0));root.innerHTML=a.length?`<div class="sale-grid">${a.map(render).join('')}</div>`:'<div class="empty-listings"><strong>No sales yet.</strong><p>Paid shipped orders and completed pickup sales will appear here.</p></div>';}catch(e){console.error(e);root.innerHTML='<div class="empty-listings">Sales could not load.</div>';}}
onAuthStateChanged(auth,u=>{if(!u){root.innerHTML='<div class="empty-listings"><strong>Sign in to see your sales.</strong></div>';return;}loadSales(u);});
root.addEventListener('click',async e=>{const button=e.target.closest('[data-mark-shipped]');if(!button)return;const u=auth.currentUser,id=button.dataset.markShipped;if(!u||!id)return;if(!confirm('Mark this order as shipped? This will update the buyer’s purchase status.'))return;const old=button.textContent;try{button.disabled=true;button.textContent='Marking Shipped…';const ref=doc(db,'offers',id),snap=await getDoc(ref);if(!snap.exists())throw new Error('Sale not found');const o=snap.data();if(o.sellerId!==u.uid||o.status!=='accepted'||o.fulfillmentMethod!=='shipping'||!['paid','paid_test','ready_to_ship'].includes(o.checkoutStage))throw new Error('Sale is not ready to ship');await updateDoc(ref,{checkoutStage:'shipped',shippedAt:serverTimestamp(),updatedAt:serverTimestamp()});await loadSales(u);}catch(err){console.error(err);button.disabled=false;button.textContent=old;alert('This order could not be marked shipped yet. If Firebase blocks it, we will update the rule.');}});
function render(o){const method=o.fulfillmentMethod==='pickup'?'Local Pickup':o.fulfillmentMethod==='shipping'?'Shipping':'Sale';const s=stateInfo(o);const shipButton=o.status==='accepted'&&o.fulfillmentMethod==='shipping'&&['paid','paid_test','ready_to_ship'].includes(o.checkoutStage)?`<button class="mini-btn sold" data-mark-shipped="${esc(o.id)}">Mark Shipped</button>`:'';return `<article class="sale-card"><span class="sale-state">${esc(s.label)}</span><h3>${esc(o.listingTitle||'Sale')}</h3><p class="sale-price">$${Number(o.counterAmount||o.amount||0).toFixed(2)}</p><p><strong>Transaction:</strong> ${esc(orderNo(o))}<br><strong>Updated:</strong> ${esc(dateText(o))}<br><strong>Delivery:</strong> ${esc(method)}</p><div class="sale-note"><strong>${s.title}</strong><p>${esc(s.note)}</p></div><div class="listing-actions"><a class="mini-btn edit" href="messages.html">Messages</a>${shipButton}</div></article>`;}